# https://github.com/marketplace?type=actions
name: "Execução Manual"

# Gatilhos/triggers: Regras de disparo
# Gatilho manual = workflow_dispatch
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

# Tarefas dentro da pipeline são chamados de jobs
jobs:
  # Nome do job
  e2e-tests:
    # Maquina onde o job vai rodar
    runs-on: self-hosted

    # Passos do job(e2e-tests) são chamados de steps
    steps:
    # Clone do projeto usando uma action que já existe no marketplace do github
      - uses: actions/checkout@v4

    # Instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

    # Tnstalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

    # Instalação das dependências
      - name: Instalando dependências
        run: yarn

    # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install

    # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      - name: Armazenando relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: ./playwright-report/